#
# generic embedded system library switches
#

ARCH_CORTEX = 1
PROC_FAMILY_STM32 = 1
PROC_STM32F7 = 1

# basic arch/driver system configs
CONFIG_SYS_TIME_64_BIT = 1
CONFIG_MEMOPS = 1
CONFIG_VARCALL = 1
CONFIG_IO = 1
CONFIG_MATH = 0
CONFIG_CRC = 1
CONFIG_WDOG = 0
CONFIG_RTC = 0
CONFIG_SYS_USE_RTC = 0
CONFIG_I2C = 0
CONFIG_I2C_DEVICE = 0
CONFIG_GPIO = 0
CONFIG_UART = 1
CONFIG_SPI = 0
CONFIG_SPI_DEVICE = 0
CONFIG_USB_VCD = 0

# software libraries
CONFIG_MINIUTILS = 1
CONFIG_TASK_QUEUE = 1
CONFIG_RINGBUFFER = 1
CONFIG_SHARED_MEM = 0
CONFIG_BOOTLOADER = 0
CONFIG_GEN_TIMER = 0
CONFIG_OS = 0

# peripheral drivers 
CONFIG_LSM303 = 0
CONFIG_M24M01 = 0
CONFIG_STMPE811 = 0
CONFIG_ADXL345 = 0
CONFIG_HMC5883L = 0
CONFIG_ITG3200 = 0
CONFIG_WIFI232 = 0
CONFIG_SPI_FLASH = 0
CONFIG_SPI_FLASH_M25P16 = 0
CONFIG_SPI_DEVICE_OS = 0
CONFIG_SPI_FLASH_OS = 0
CONFIG_NRF905 = 0

# CLI
CONFIG_CLI = 1
CONFIG_CLI_SYS_OFF = 0
CONFIG_CLI_BUS_OFF = 1
CONFIG_CLI_DEV_OFF = 1
CONFIG_CLI_GPIO_OFF = 1
CONFIG_CLI_RTC_OFF = 1
CONFIG_CLI_HMC5883L_OFF = 1
CONFIG_CLI_ADXL345_OFF = 1
CONFIG_CLI_M24M01_OFF = 1
CONFIG_CLI_ITG3200_OFF = 1

include ${gensysdir}/include.mk
